@API_HostAddress = http://localhost:5067

GET {{API_HostAddress}}/api/users
Accept: application/json
Authorization: Bearer {{token}}


POST  {{API_HostAddress}}/api/account/register
Accept: application/json
Content-Type: application/json
{
  "username": "rosalyn",
  "password": "Pa$$w0rd"
}

# @name login
POST  {{API_HostAddress}}/api/account/login
Accept: application/json
Content-Type: application/json

{
  "username": "melinda",
  "password": "Pa$$w0rd"
}

@token = {{login.response.body.token}}
 
GET  {{API_HostAddress}}/api/buggy/server-error
Accept: application/json
